(module
  (func (export "calcFizzbuzz") (param $n i32) (result i32)
    ;; n % 15 == 0 -> 3 (fizzbuzz)
    (if (i32.eqz (i32.rem_u (local.get $n) (i32.const 15)))
      (then (return (i32.const 3))))
    ;; n % 3 == 0 -> 1 (fizz)
    (if (i32.eqz (i32.rem_u (local.get $n) (i32.const 3)))
      (then (return (i32.const 1))))
    ;; else -> 2 (fake default until rule 4)
    (i32.const 2)))
